name: Math Library Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Maven Command -  mvn clean
        run: mvn clean
      - name: Testing - mvn test
        run: mvn test


